name: Deploy to EC2

on:
  workflow_run:
    workflows:
      - Build and Push Docker Image CI
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download tag artifact from CI
        uses: actions/download-artifact@v6
        with:
          name: release-tag
          path: .

      - name: Read tag
        run: |
          IMAGE_TAG=$(cat tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "Deploying tag: $IMAGE_TAG"

      - name: Deploy application on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            APP_DIR=/home/ubuntu/app
            REPO_URL=https://github.com/obijzbo/fastapi-sample-project.git

            if [ ! -d "$APP_DIR/.git" ]; then
              git clone $REPO_URL $APP_DIR
            else
              cd $APP_DIR
              git pull origin main
            fi

            cd $APP_DIR
            IMAGE_TAG=${IMAGE_TAG} docker compose pull
            IMAGE_TAG=${IMAGE_TAG} docker compose up -d --remove-orphans
