name: Build and Push Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Set IMAGE_TAG
      #   id: set_tag
      #   run: |
      #     echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      #     echo "${GITHUB_REF#refs/tags/}" > tag.txt

      - name: Build Docker Image and Push
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-sample-project:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-sample-project:$IMAGE_TAG

      - name: Set IMAGE_TAG
        id: set_tag
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$IMAGE_TAG" > $GITHUB_ENV

      # - name: Upload tag artifact
      #   uses: actions/upload-artifact@v6
      #   with:
      #     name: release-tag
      #     path: tag.txt

      - name: Deploy application on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            APP_DIR=/home/ubuntu/app
            REPO_URL=https://github.com/obijzbo/fastapi-sample-project.git

            echo "Deployment tag: ${IMAGE_TAG}"

            if [ ! -d "$APP_DIR/.git" ]; then
              git clone $REPO_URL $APP_DIR
            else
              cd $APP_DIR
              git pull origin main
            fi

            cd $APP_DIR
            export IMAGE_TAG=${IMAGE_TAG}
            docker compose pull
            docker compose down
            docker compose up -d --remove-orphans

          